### ISSUE TITLE
Upload via Arduino 1.7.9 does not work ...

### ISSUE THREAD

**Issue by fesch** [MalyanSystem/Malyan-M180-Marlin#1]
Hi

This may not be an issue but just a lack of documentation: I don't get the firmware uploaded to the printer. What I did:
- power off the printer
- press the center button
- power on the printer
- release the center button
- open Arduino IDE
- select the correct port
- select the ATMEGA2560 board
- compiling (no errors)
- uploading --> avrdude: stk500v2_ReceiveMessage(): timeout

Did I miss something?

**Comment by yongzong** [comment]
For older boot-loader, need to hold center button.
New boot-loader you can release button after power on.

Procedure seems OK, double check baud-rate is 57600.

2016-04-23 21:23 GMT+08:00 Bob Fisch notifications@github.com:

**Comment by fesch** [comment]
Can't get it to work :-(
I even installed a Windows PC, because there setting the port seed is possible (no settings in OSX), but that didn't help either. I'm always suck with a timeout.

On the printer the display indicates "update firmware". If I press the center button again, it says "upgrading" and the backlight of the button turn blue. The timeout remains in both situations :-|

**Comment by yongzong** [comment]
Did you tried using standalone avrdude to flash?

2016-04-23 23:28 GMT+08:00 Bob Fisch notifications@github.com:

**Comment by fesch** [comment]
Not yet. Will to that this evening then ...

**Comment by fesch** [comment]
Same result :-(

```
OSX:bin user$ ./avrdude -C"/Users/user/Arduino/Arduino.org 1.7.9.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf" -v -patmega2560 -cwiring -P/dev/tty.wchfa140 -b57600 -D -Uflash:w:/var/folders/vf/nj4mlpzj62lc4_09_rwc6vp40000gn/T/build7114193274732879231.tmp/Marlin.cpp.hex

avrdude: Version 6.0.1, compiled on Jan 15 2015 at 12:42:51
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2009 Joerg Wunsch

         System wide configuration file is "/Users/user/Arduino/Arduino.org 1.7.9.app/Contents/Java/hardware/tools/avr/etc/avrdude.conf"
         User configuration file is "/Users/user/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/tty.wchfa140
         Using Programmer              : wiring
         Overriding Baud Rate          : 57600
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_ReceiveMessage(): timeout
avrdude: stk500v2_getsync(): timeout communicating with programmer

avrdude done.  Thank you.

```

**Comment by fesch** [comment]
I usually get such a timeout when I have selected the wrong Board.

Is it sure that the M180 has an ATmega 2560? I read somewhere it had only the ATmega 1280 installed. Maybe I should open the printer and take a look at it ;-)

**Comment by yongzong** [comment]
1. M180 have ATmega2560. Please use "-p m2560". Only 2011~early 2012
   machines uses mega1280
2. Programmer should be "-c stk500v1"
   Please let me know if it work.

2016-04-24 3:05 GMT+08:00 Bob Fisch notifications@github.com:

**Comment by fesch** [comment]
Flashing works :-) Thanks! ... although the screen remains blank after restarting the printer ...
